# Generated by Django 3.1 on 2021-01-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadDwonload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/images')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/image/')),
            ],
        ),
    ]
